version: "3"

services:
  web:
    image: sorididim11/web_counter:1.0
    ports:
      - "5000:5000"
    networks:
      - webnet
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - webnet
      - mybridge

# for compatiblity between single host and swarm, omitting driver is good strategy because default driver
# depending on bridge on single host, overlay on swarm
networks:
  webnet:
  mydefault:
    #driver: bridge       #it can be created when using swarm, but service can't be launched 

