version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: sorididim11/web_counter:1.0
    ports:
      - "5000:5000"
    networks:
      - webnet
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - webnet
    
networks:
  webnet: