version: "3"

services:
  rng:
    build: rng
    ports:
    - "8001:80"
    # networks:
    #   - coins-net

  hasher:
    build: hasher
    ports:
    - "8002:80"

  webui:
    build: webui
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis
    volumes:
      - "myvol:/var/lib/redis"

  worker:
    build: worker
    # networks:
    #   - coins-net
volumes:
  coins-redis-vol:
    driver: local
# networks:
#   coins-net:

